spring:
    application:
        name: waiting
    datasource:
        url: jdbc:h2:tcp://localhost/~/redistest
        username: sa
        password: 1234
    jpa:
        hibernate:
            ddl-auto: create
        properties:
          hibernate:
              format_sql: true
    cache:
        type: redis
    data:
        redis:
            host: localhost
            port: 6379
